version: '3'
services:
  dev:
    image: shadowcljs-base:11
    volumes:
      - .:/app
    working_dir: /app
    command: npm run watch
    ports:
      - 8700:8700
      - 8777:8777
      - 9630:9630