version: '2'
services:
  base:
    image: node:11-alpine
    volumes:
      - .:/app
    working_dir: /app

  install:
    extends:
      service: base
    command: npm i

  build:
    extends:
      service: base
    command: npm run build

  create-bundles:
    extends:
      service: base
    command: npm run create-bundles