version: '3'
services:
  dev:
    build: .
    volumes:
      - ..:/app
      - ~/.ssh:/.ssh-localhost:ro
    working_dir: /app
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8700:8700
      - 8777:8777
      - 9630:9630